name: Publish release

on:
  release:
    types: [created]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      # access it through ${{ steps.get_version.outputs.VERSION }}
    - name: Build docker image
      run: |-
        docker build -t "docker.pkg.github.com/${{ github.actor }}/${{ github.event.repository.name }}/system:${{ steps.get_version.outputs.VERSION }}" .
    - name: Login
      run: |-
        echo $GITHUB_TOKEN | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Push
      run: |-
        docker push "docker.pkg.github.com/${{ github.actor }}/${{ github.event.repository.name }}/system:${{ steps.get_version.outputs.VERSION }}"
