name: Publish release

on:
  release:
    types: [created]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      # access it through ${{ steps.get_version.outputs.VERSION }}
    - name: Build and push
      uses: matootie/github-docker@v2.2.2
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        imageTag: ${{ steps.get_version.outputs.VERSION }}
